# Generated by Django 5.2.3 on 2025-06-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='score',
        ),
    ]
