# Generated by Django 5.2.3 on 2025-07-11 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['region', 'name']},
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('title', 'artist')},
        ),
        migrations.AddField(
            model_name='artist',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='songs.musicregion'),
        ),
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together={('name', 'region')},
        ),
    ]
