# Generated by Django 5.2.3 on 2025-07-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_musicregion_alter_artist_options_rating_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_cover',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
