# Generated by Django 5.2.3 on 2025-08-11 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_set_db_collation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', 'score'], name='songs_ratin_user_id_82ff44_idx'),
        ),
    ]
