# Generated by Django 5.2.3 on 2025-08-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_rating_songs_ratin_user_id_82ff44_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankView',
            fields=[
                ('rank_id', models.IntegerField(primary_key=True, serialize=False)),
                ('artist_id', models.IntegerField()),
                ('artist_name', models.CharField(max_length=100)),
                ('region_id', models.IntegerField()),
                ('song_id', models.IntegerField()),
                ('song_title', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('rank_artist', models.IntegerField()),
                ('order_artist', models.IntegerField()),
                ('rank_all', models.IntegerField()),
                ('order_all', models.IntegerField()),
            ],
            options={
                'db_table': 'rank_view',
                'managed': False,
            },
        ),
    ]
