# Generated by Django 5.2.3 on 2025-10-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_rankview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSongView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.IntegerField()),
                ('artist_name', models.CharField(max_length=100)),
                ('region_id', models.IntegerField()),
                ('artist_format_name', models.CharField(blank=True, max_length=100, null=True)),
                ('song_id', models.IntegerField()),
                ('song_title', models.CharField(max_length=100)),
                ('is_cover', models.BooleanField(blank=True, null=True)),
                ('song_format_title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'artist_song_view',
                'managed': False,
            },
        ),
    ]
