# Generated by Django 5.2.3 on 2026-04-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0014_song_year'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='song',
            new_name='songs_song_lyricis_60d634_idx',
            old_name='songs_song_lyricis_idx',
        ),
        migrations.RenameIndex(
            model_name='song',
            new_name='songs_song_compose_77aa7f_idx',
            old_name='songs_song_compose_idx',
        ),
        migrations.RenameIndex(
            model_name='song',
            new_name='songs_song_year_d5825d_idx',
            old_name='songs_song_year_idx',
        ),
        migrations.AddField(
            model_name='rating',
            name='karaoke_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
