# Generated by Django 5.2.3 on 2026-04-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0015_rename_songs_song_lyricis_idx_songs_song_lyricis_60d634_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='karaoke_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
