# Generated by Django 5.2.3 on 2026-04-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0016_alter_rating_karaoke_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
