# Generated by Django 5.2.3 on 2026-05-02 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0018_drop_rankview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtistSongView',
        ),
    ]
