"""
名義（ArtistCredit）テーブルを追加し、Song から参照できるようにする。

Song.credit は最終的に NOT NULL にするが、既存行を埋める必要があるため
ここではいったん NULL 許容で追加する。
  0021: 器を作る（このファイル）
  0022: 既存データを埋める
  0023: NOT NULL にする
"""

# Generated by Django 5.2.17 on 2026-08-16 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0020_userprofile_one_to_one"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "format_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="songs.artist",
                    ),
                ),
            ],
            options={
                "ordering": ["artist", "-is_primary", "name"],
            },
        ),
        migrations.AddField(
            model_name="song",
            name="credit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="songs",
                to="songs.artistcredit",
            ),
        ),
        migrations.AddIndex(
            model_name="artistcredit",
            index=models.Index(
                fields=["format_name"], name="songs_artis_format__77eb57_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="artistcredit",
            unique_together={("artist", "name")},
        ),
    ]
