"""
Song.credit を NOT NULL にする（0021→0022 の仕上げ）。

NULL を「主名義」の意味で使わないための措置。MySQL の UNIQUE インデックスは
NULL 同士を別の値として扱うため、将来セルフカバーを別曲として持つために
unique_together を ("title", "artist", "credit") に広げたとき、credit が
NULL 可のままだと主名義の曲で重複防止が効かなくなってしまう。

0022 で全曲に credit が入っている前提。NULL が残っているとここで失敗する。
"""

# Generated by Django 5.2.17 on 2026-08-16 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0022_populate_artist_credits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="credit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="songs",
                to="songs.artistcredit",
            ),
        ),
    ]
