"""
別表記（ArtistAlias）テーブルを追加する。

0022 が Artist.format_name から救出した ArtistCredit 行 124 件のうち、
89 件は「名義」ではなく単なる別表記だった（ビートルズ / The Beatles、
髙橋真梨子 / 高橋真梨子 など）。その受け皿。

  0024: 器を作る（このファイル）
  0025: ArtistCredit から該当 89 件を移す
"""

# Generated by Django 5.2.17 on 2026-08-16 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0023_song_credit_not_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "format_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("symbol", "記号・空白の違い"),
                            ("script", "英字・原語表記"),
                            ("kana", "読み・カナ表記"),
                            ("order", "語順・区切りの違い"),
                            ("variant", "異体字"),
                            ("other", "その他の表記ゆれ"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="songs.artist",
                    ),
                ),
            ],
            options={
                "ordering": ["artist", "name"],
                "indexes": [
                    models.Index(
                        fields=["format_name"], name="songs_artis_format__c40507_idx"
                    )
                ],
                "unique_together": {("artist", "name")},
            },
        ),
    ]
