"""
Django settings for music project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from decouple import config
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# .env で切り替える。書き忘れた場合は安全側（False）に倒れる。
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "sugar191.pythonanywhere.com", "SotaroPC"]

# --- CSRF / HTTPS -----------------------------------------------------------
# 本番(PythonAnywhere)は前段でSSLを終端し、Djangoには HTTP として渡ってくる。
# これを教えないと request.scheme が "http" のままになり、
# ブラウザが送る Origin: https://... と食い違って POST が
# 「CSRF検証に失敗したため、リクエストは中断されました」(400) になる。
#
# このヘッダは「信頼できるプロキシが必ず付け直す」前提でのみ安全なので、
# 開発(DEBUG=True, 素のrunserver)では有効にしない。
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Django 4.0以降、POST時に Origin ヘッダがあればこの一覧と照合される。
# スキーム込みで書く必要がある。
CSRF_TRUSTED_ORIGINS = ["https://sugar191.pythonanywhere.com"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "songs",
    "import_export",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.BasicAuthentication",  # ←B用
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# 書き込み系API（songs/create_with_artist, songs/update_credits）に
# 認証を要求するかどうか。長らく AllowAny のままだったものを閉じるための移行フラグ。
#
# 外部クライアント（WindowsGUI / Androidアプリ）がトークンを送るように
# なるまでは False、両方の更新を確認できたら True にする。
# 未設定時は安全側（True＝認証必須）に倒れるので、
# 移行期間中は本番・開発どちらの .env にも明示的に False を書いておくこと。
#
# 変更を反映するにはプロセスの再起動が必要（デコレータは起動時に評価されるため）。
REQUIRE_API_AUTH = config("REQUIRE_API_AUTH", default=True, cast=bool)

MIDDLEWARE = [
    # レスポンス本文を書き換える他のミドルウェアより先に置く必要がある
    "django.middleware.gzip.GZipMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "music.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.csrf",
            ],
        },
    },
]

WSGI_APPLICATION = "music.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="3306"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# 静的ファイルの収集先ディレクトリを設定
STATIC_ROOT = BASE_DIR / "staticfiles"

# 静的ファイルの場所
STATICFILES_DIRS = [
    BASE_DIR / "static",  # プロジェクト内の静的ファイルディレクトリ
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000

# 開発時のみ：実行されたSQLと所要時間をコンソールに出す（遅い画面の切り分け用）。
# 不要になったらこのブロックごと削除してよい。
if DEBUG:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {"console": {"class": "logging.StreamHandler"}},
        "loggers": {
            "django.db.backends": {"handlers": ["console"], "level": "DEBUG"},
        },
    }

# 末尾スラッシュは必須。省くと APPEND_SLASH による 301 が毎回挟まり、
# しかもブラウザに恒久キャッシュされてURL変更時に厄介になる。
LOGIN_URL = "/login/"  # @login_required の飛び先（既定の /accounts/login/ を上書き）
LOGIN_REDIRECT_URL = "/ranking/"  # ログイン後のリダイレクト先URL
LOGOUT_REDIRECT_URL = "/login/"  # ログアウト後のリダイレクト先

# /api/dump/* を叩くための共有トークン。ソースに直書きせず .env で管理する。
# 未設定なら空文字になり、views_dump 側で全リクエストを 401 にする。
EXPORT_API_TOKEN = config("EXPORT_API_TOKEN", default="")

RATING_CACHE_DIR = BASE_DIR / "exports"
